# Generated by Django 3.2.9 on 2021-12-06 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=255, null=True)),
                ('release', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_name', models.CharField(max_length=255, null=True)),
                ('album_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.artist')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='related_artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.artist'),
        ),
    ]
